num1=input('enter a number:')
num2=input('enter another number:')
sum = float(num1)+float(num2)
product =float(num1)* float(num2)
difference=float(num1)- float(num2)
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))
print('The product of {0} and {1} is {2}'.format(num1, num2, product))
print('The difference of {0} and {1} is {2}'.format(num1, num2, difference))
c=input('press close to quit')
